AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  resume-backend

  Sample SAM Template for resume-backend
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  IncrementViewsApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub api-${Stage}.wbresume.frozen-phoenix.com
      ValidationMethod: DNS

  IncrementViewsApiDeployment:
    Type: AWS::Serverless::Api
      Properties:
        StageName: !Ref Stage

  IncrementViewsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: increment-views/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref IncrementViewsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref IncrementViewsTable
          REGION: !Sub ${AWS::Region}
      Cors: "'www.wbresume.frozen-phoenix.com'"
      Domain:
        DomainName: !Sub api-${Stage}.wbresume.frozen-phoenix.com
        CertificateArn: !Ref IncrementViewsApiCertificate
        Route53:
          HostedZoneName: "frozen-phoenix.com."
      Events:
        IncrementViews:
          Type: Api
          Properties:
            Path: /increment
            Method: post
            RestApiId: !Ref IncrementViewsApiDeployment

  IncrementViewsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${AWS::StackName}-IncrementViews

Outputs:
  IncrementViewsApi:
    Description: "API Gateway endpoint URL for Prod stage for Increment Views function"
    Value: !Sub "https://${IncrementViewsApiDeployment}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/increment/"
  IncrementViewsFunction:
    Description: "Increment Views Lambda Function ARN"
    Value: !GetAtt IncrementViewsFunction.Arn
  IncrementViewsFunctionIamRole:
    Description: "Implicit IAM Role created for Increment Views function"
    Value: !GetAtt IncrementViewsFunctionRole.Arn
